# Generated by Django 6.0.5 on 2026-05-26 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('sap', 'SAP fuel/procurement'), ('utility', 'Utility electricity'), ('travel', 'Corporate travel')], max_length=20)),
                ('ingestion_method', models.CharField(choices=[('csv_upload', 'CSV upload'), ('api_pull', 'API pull'), ('manual', 'Manual entry')], max_length=20)),
                ('external_id', models.CharField(blank=True, max_length=150, null=True)),
                ('file_name', models.CharField(blank=True, max_length=200, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='ingestion.client')),
            ],
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row_id', models.CharField(blank=True, max_length=200, null=True)),
                ('source_category', models.CharField(blank=True, max_length=100, null=True)),
                ('scope', models.CharField(choices=[('scope_1', 'Scope 1'), ('scope_2', 'Scope 2'), ('scope_3', 'Scope 3')], max_length=20)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('facility_code', models.CharField(blank=True, max_length=100, null=True)),
                ('origin', models.CharField(blank=True, max_length=100, null=True)),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
                ('mode', models.CharField(blank=True, max_length=50, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('quantity_unit', models.CharField(blank=True, max_length=30, null=True)),
                ('normalized_quantity', models.FloatField(blank=True, null=True)),
                ('normalized_unit', models.CharField(blank=True, max_length=30, null=True)),
                ('emission_kg_co2e', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('raw_row', models.JSONField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('locked_for_audit', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.client')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.importbatch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
